apiVersion: v1
kind: Pod
metadata:
  name: dhealth-pod-training
spec:
    volumes:
      - name: dh-volume
        persistentVolumeClaim:
          claimName: dhealth-pvc
    containers:
    - name: dhealth-pylibs
      image: dhealth/pylibs:latest
      volumeMounts:
        - name: dh-volume
          mountPath: /deephealth
      command: ["/bin/bash", "-c", "export OUTPUT_DIR=/deephealth/outputs; mkdir $OUTPUT_DIR/trash; python3 /deephealth/use_case_pipeline/python/skin_lesion_segmentation_training.py /deephealth/dataset/isic_segmentation/isic_segmentation.yml --out-dir $OUTPUT_DIR --epochs 1 --batch-size 2"]
      resources:
        limits:
          memory: "3072Mi"
          cpu: "3000m"
    restartPolicy: Never