apiVersion: batch/v1
kind: Job
metadata:
  name: dhealth-job-splityaml
spec:
  completions: 1
  ttlSecondsAfterFinished: 0 #to be automatically deleted, 0 seconds after it finishes.
  template:
    metadata:
      name: dhealth-pod-splityaml-$PARTNUMBER
    spec:
      volumes:
        - name: dhealth-volume
          persistentVolumeClaim:
            claimName: dhealth-pvc
      containers:
      - name: split-yaml
        image: dhealth/split-yaml:latest
        volumeMounts:
          - name: dhealth-volume
            mountPath: /deephealth
        args:
        - '$PODINPUT'
        - '$PARTNUMBER'
        - '$PODOUTPUT'
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
      restartPolicy: Never