apiVersion: batch/v1
kind: Job
metadata:
  name: dh-job-clean-up
spec:
  completions: 1
  ttlSecondsAfterFinished: 0 #to be automatically deleted, 0 seconds after it finishes.
  template:
    metadata:
      name: dh-clean-up
    spec:    
      volumes:
        - name: dh-volume
          persistentVolumeClaim:
            claimName: dh-pv-claim
      containers:
      - name: command-cleanup-container
        image: debian
        volumeMounts:
          - name: dh-volume
            mountPath: /deephealth
        command: ["/bin/bash", "-c", "rm -f $PODOUTPUT/part-*"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "125m"
      restartPolicy: Never