apiVersion: v1
kind: Pod
metadata:
  name: dh-pod-inference
  namespace: dh
spec:
    volumes:
      - name: dh-volume
        persistentVolumeClaim:
          claimName: dh-pv-claim
    containers:
    - name: dhealth-pylibs
      image: dhealth/pylibs:latest
      volumeMounts:
        - name: dh-volume
          mountPath: /deephealth
      command: ["/bin/bash", "-c", "cd /deephealth/examples/use_case_pipeline && python3 skin_lesion_segmentation_inference.py '../../dataset/isic_segmentation/isic_segmentation.yml' 'isic_segm_checkpoint.bin' --out-dir '../../outputs' --batch-size 2 && sleep 5"]
      resources:
        limits:
          memory: "2048Mi"
          cpu: "2000m"
    restartPolicy: Never
