apiVersion: v1
kind: Pod
metadata:
  name: dh-pod-inference
spec:
  volumes:
  - name: dh-volume
    persistentVolumeClaim:
      claimName: dh-pv-claim
  containers:
  - name: dhealth-pylibs
    image: dhealth/pylibs:latest
    volumeMounts:
    - name: dh-volume
      mountPath: /deephealth
    command: ["/bin/bash", "-c", "export OUTPUT_DIR=/deephealth/outputs; mkdir $OUTPUT_DIR/trash; python3 /deephealth/examples/use_case_pipeline/skin_lesion_segmentation_inference.py /deephealth/dataset/isic_segmentation/isic_segmentation.yml /deephealth/examples/use_case_pipeline/isic_segm_checkpoint.bin --out-dir $OUTPUT_DIR --batch-size 2"]
    resources:
      limits:
        memory: "3072Mi"
        cpu: "3000m"
  restartPolicy: Never